### ISSUE TITLE
Exclude only for indexing purpose

### ISSUE THREAD

**Issue by sondreb** [gruehle/exclude-folders#7]
The main reason to use this plugin is to avoid the full text indexing of source files within the npm/bower package folders. I kept getting warnings in Brackets regarding this when searching.

The extension removes the folders from the project, they are no longer visible. There should be an option to hide/show the excluded folders.

**Comment by demisx** [comment]
+1. We need to be able to exclude `node_modules/` from indexing, but have it visible in the project tree itself.

**Comment by gruehle** [comment]
@sondreb @demisx - I agree, but that is beyond the scope of this extension. Please upvote [this Trello card](https://trello.com/c/zd77LxFS/1229-2s-file-exclusion-filtering-beyond-find-in-files), which is the correct way to solve this issue.
